// -----------------------------------------------------------------------
// <copyright file="GlobalSuppressions.cs" company="NaoUnderscore">
// Copyright (c) NaoUnderscore. All rights reserved.
// Licensed under the CC BY-SA 3.0 license.
// </copyright>
// -----------------------------------------------------------------------

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1648:inheritdoc should be used with inheriting class", Justification = "<Pending>", Scope = "member", Target = "~M:RolePlus.ExternModule.API.Engine.Components.AEnvironmentMeshComponent.#ctor(MapEditorReborn.API.Features.Objects.SchematicObject,UnityEngine.Vector3,UnityEngine.Vector3,UnityEngine.Quaternion)")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1648:inheritdoc should be used with inheriting class", Justification = "<Pending>", Scope = "member", Target = "~M:RolePlus.ExternModule.API.Engine.Components.AEnvironmentMeshComponent.#ctor(UnityEngine.GameObject)")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1648:inheritdoc should be used with inheriting class", Justification = "<Pending>", Scope = "member", Target = "~M:RolePlus.ExternModule.API.Engine.Components.AEnvironmentMeshComponent.#ctor(UnityEngine.Vector3,MapEditorReborn.API.Features.Objects.SchematicObject,UnityEngine.Vector3,UnityEngine.Vector3,UnityEngine.Quaternion)")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1648:inheritdoc should be used with inheriting class", Justification = "<Pending>", Scope = "member", Target = "~M:RolePlus.ExternModule.API.Engine.Components.AEnvironmentMeshComponent.#ctor(UnityEngine.Vector3,UnityEngine.Quaternion,MapEditorReborn.API.Features.Objects.SchematicObject,UnityEngine.Vector3,UnityEngine.Vector3,UnityEngine.Quaternion)")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1648:inheritdoc should be used with inheriting class", Justification = "<Pending>", Scope = "member", Target = "~M:RolePlus.ExternModule.API.Engine.Components.AEnvironmentMeshComponent.#ctor(UnityEngine.Vector3,UnityEngine.Quaternion,UnityEngine.Vector3,MapEditorReborn.API.Features.Objects.SchematicObject,UnityEngine.Vector3,UnityEngine.Vector3,UnityEngine.Quaternion)")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1648:inheritdoc should be used with inheriting class", Justification = "<Pending>", Scope = "member", Target = "~M:RolePlus.ExternModule.API.Engine.Components.AEnvironmentMeshComponent.UpdateInteractableItems(System.Boolean,System.String[])")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1648:inheritdoc should be used with inheriting class", Justification = "<Pending>", Scope = "member", Target = "~M:RolePlus.ExternModule.API.Engine.Components.ASchematicMeshComponent.#ctor(UnityEngine.GameObject)")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1648:inheritdoc should be used with inheriting class", Justification = "<Pending>", Scope = "member", Target = "~M:RolePlus.ExternModule.API.Engine.Components.ASchematicMeshComponent.#ctor(UnityEngine.GameObject,System.String)")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1648:inheritdoc should be used with inheriting class", Justification = "<Pending>", Scope = "member", Target = "~M:RolePlus.ExternModule.API.Engine.Components.ASchematicMeshComponent.PlayAnimation(System.String,System.Boolean)~System.Boolean")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1648:inheritdoc should be used with inheriting class", Justification = "<Pending>", Scope = "member", Target = "~M:RolePlus.ExternModule.API.Features.CustomRoles.RoleBehaviour.DestroyThirdPersonMesh")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1648:inheritdoc should be used with inheriting class", Justification = "<Pending>", Scope = "member", Target = "~P:RolePlus.ExternModule.API.Engine.Components.ASchematicMeshComponent.AnimatorsTriggers")]
